@startuml
hide footbox

participant "Joueur" as joueur
participant "ComposantControle" as compContr

joueur -> compContr : Envoi message : Initialisation controle
compContr -> compContr : Initialisation du processus de contrôle
compContr -> LibGDX : Injection du processus

@enduml